"""remove_workspace_id_from_users

Revision ID: 9cf52273545f
Revises: 5a0680965145
Create Date: 2026-01-11 23:50:27.303051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9cf52273545f'
down_revision: Union[str, None] = '5a0680965145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "workspace_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    # ### end Alembic commands ###
