"""token added in user table

Revision ID: 746836963f64
Revises: b573df09ec59
Create Date: 2025-11-02 18:28:07.767955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746836963f64'
down_revision: Union[str, None] = 'b573df09ec59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Changed nullable=True to allow existing rows to have NULL values
    op.add_column('users', sa.Column('token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
