"""add expires at showings

Revision ID: 6c32322aa8cb
Revises: 0ec6a7bf89e9
Create Date: 2025-11-16 17:06:31.794627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c32322aa8cb'
down_revision: Union[str, None] = '0ec6a7bf89e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showings', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showings', 'expires_at')
    # ### end Alembic commands ###
