"""Add production-ready indexes to all models

Revision ID: af136aa4df0e
Revises: 07e9ec2bd38c
Create Date: 2025-12-11 01:27:22.860088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af136aa4df0e'
down_revision: Union[str, None] = '07e9ec2bd38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_booking_seats_booking_id', 'booking_seats', ['booking_id'], unique=False)
    op.create_index('ix_booking_seats_booking_showing', 'booking_seats', ['booking_id', 'showing_id'], unique=False)
    op.create_index('ix_booking_seats_seat_id', 'booking_seats', ['seat_id'], unique=False)
    op.create_index('ix_booking_seats_showing_id', 'booking_seats', ['showing_id'], unique=False)
    op.create_index('ix_booking_seats_showing_seat', 'booking_seats', ['showing_id', 'seat_id'], unique=False)
    op.create_unique_constraint('uq_booking_seats_showing_seat', 'booking_seats', ['showing_id', 'seat_id'])
    op.create_foreign_key(None, 'booking_seats', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'booking_seats', 'seats', ['seat_id'], ['id'])
    op.create_index('ix_bookings_booking_number', 'bookings', ['booking_number'], unique=False)
    op.create_index('ix_bookings_created_at', 'bookings', ['created_at'], unique=False)
    op.create_index('ix_bookings_showing_id', 'bookings', ['showing_id'], unique=False)
    op.create_index('ix_bookings_showing_status', 'bookings', ['showing_id', 'status'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_index('ix_bookings_user_status', 'bookings', ['user_id', 'status'], unique=False)
    op.create_index('ix_movies_genre', 'movies', ['genre'], unique=False)
    op.create_index('ix_movies_language', 'movies', ['language'], unique=False)
    op.create_index('ix_movies_rating', 'movies', ['rating'], unique=False)
    op.create_index('ix_movies_release_date', 'movies', ['release_date'], unique=False)
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.create_index('ix_seats_seat_type', 'seats', ['seat_type'], unique=False)
    op.create_index('ix_seats_theater_id', 'seats', ['theater_id'], unique=False)
    op.create_index('ix_seats_theater_row_column', 'seats', ['theater_id', 'row', 'column'], unique=False)
    op.create_unique_constraint('uq_seats_theater_row_column', 'seats', ['theater_id', 'row', 'column'])
    op.create_index('ix_showings_expires_active', 'showings', ['expires_at', 'is_active'], unique=False)
    op.create_index('ix_showings_expires_at', 'showings', ['expires_at'], unique=False)
    op.create_index('ix_showings_is_active', 'showings', ['is_active'], unique=False)
    op.create_index('ix_showings_movie_id', 'showings', ['movie_id'], unique=False)
    op.create_index('ix_showings_movie_theater_datetime', 'showings', ['movie_id', 'theater_id', 'show_start_datetime'], unique=False)
    op.create_index('ix_showings_theater_id', 'showings', ['theater_id'], unique=False)
    op.create_index('ix_showings_theater_movie', 'showings', ['theater_id', 'movie_id'], unique=False)
    op.create_index('ix_theaters_city', 'theaters', ['city'], unique=False)
    op.create_index('ix_theaters_city_location', 'theaters', ['city', 'location'], unique=False)
    op.create_index('ix_theaters_location', 'theaters', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_theaters_location', table_name='theaters')
    op.drop_index('ix_theaters_city_location', table_name='theaters')
    op.drop_index('ix_theaters_city', table_name='theaters')
    op.drop_index('ix_showings_theater_movie', table_name='showings')
    op.drop_index('ix_showings_theater_id', table_name='showings')
    op.drop_index('ix_showings_movie_theater_datetime', table_name='showings')
    op.drop_index('ix_showings_movie_id', table_name='showings')
    op.drop_index('ix_showings_is_active', table_name='showings')
    op.drop_index('ix_showings_expires_at', table_name='showings')
    op.drop_index('ix_showings_expires_active', table_name='showings')
    op.drop_constraint('uq_seats_theater_row_column', 'seats', type_='unique')
    op.drop_index('ix_seats_theater_row_column', table_name='seats')
    op.drop_index('ix_seats_theater_id', table_name='seats')
    op.drop_index('ix_seats_seat_type', table_name='seats')
    op.drop_index('ix_movies_title', table_name='movies')
    op.drop_index('ix_movies_release_date', table_name='movies')
    op.drop_index('ix_movies_rating', table_name='movies')
    op.drop_index('ix_movies_language', table_name='movies')
    op.drop_index('ix_movies_genre', table_name='movies')
    op.drop_index('ix_bookings_user_status', table_name='bookings')
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_showing_status', table_name='bookings')
    op.drop_index('ix_bookings_showing_id', table_name='bookings')
    op.drop_index('ix_bookings_created_at', table_name='bookings')
    op.drop_index('ix_bookings_booking_number', table_name='bookings')
    op.drop_constraint(None, 'booking_seats', type_='foreignkey')
    op.drop_constraint(None, 'booking_seats', type_='foreignkey')
    op.drop_constraint('uq_booking_seats_showing_seat', 'booking_seats', type_='unique')
    op.drop_index('ix_booking_seats_showing_seat', table_name='booking_seats')
    op.drop_index('ix_booking_seats_showing_id', table_name='booking_seats')
    op.drop_index('ix_booking_seats_seat_id', table_name='booking_seats')
    op.drop_index('ix_booking_seats_booking_showing', table_name='booking_seats')
    op.drop_index('ix_booking_seats_booking_id', table_name='booking_seats')
    # ### end Alembic commands ###
