"""add expires_at to locked_seats

Revision ID: dd4a8ac7da4c
Revises: af136aa4df0e
Create Date: 2025-12-19 02:18:46.710136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4a8ac7da4c'
down_revision: Union[str, None] = 'af136aa4df0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locked_seats', sa.Column('expires_at', sa.DateTime(), nullable=False, server_default=sa.text("(CURRENT_TIMESTAMP + INTERVAL '10 minutes')")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locked_seats', 'expires_at')
    # ### end Alembic commands ###
