"""Description of changes

Revision ID: b86af099cbf9
Revises: 
Create Date: 2026-01-07 11:44:19.159086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b86af099cbf9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('workspaces', 'members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('members', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'workspace_id')
    # ### end Alembic commands ###
